server:
  port: 9100

sa-token:
  sso:
    # (模式三)打开
    is-http: true
    # API 接口调用秘钥
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # 允许单点登录的url（防止重定向到非法页面）
    allow-url: http://sso-*.com*
  #  #指定时间后token一定失效，不管登录用户是否一直访问系统
#  timeout:
  # 登录用户持续30分钟没有操作系统，token就失效
  activity-timeout: 1800
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  is-read-cookie: false
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    database: 13
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 10s

#spring:
#  # redis配置
#  redis:
#    database: 14
#    host: 127.0.0.1
#    port: 6379
#    password: root
#    timeout: 10s
